#!/usr/bin/env python3
"""consolidated.json -> issue_manifest.json (the issue specs file_issues.sh files).

Structure (round-2 design, per user spec):
  MASTER epic
    +- area epic (one per area: holds non-autofix high/medium individual issues,
    |             one low+info bucket, and retrofitted prior-round issues)
    +- autofix epic (one per-severity bucket issue, all auto-fixables)
    +- observer issues (one per non-autofix severity: a #-listing index)

Overlap handling: findings whose fingerprint is in dupe_map.json are NOT filed as
new issues; instead links_existing maps the prior issue -> its area epic so
file_issues.sh links it in. Re-runnable: keys are stable; file_issues.sh is idempotent.
"""

import json
from collections import Counter, defaultdict

RUN = "2026-06-03"
RUNDIR = f"qa/super-qa/runs/{RUN}"
CONS = f"{RUNDIR}/consolidated.json"
DUPE = "qa/super-qa/dupe_map.json"
OUT = f"{RUNDIR}/issue_manifest.json"

# areas that exist ONLY in the prior round (no new findings) but still need an epic
# so retrofitted old issues have a parent. (papers/mcp were in #181-233, out of this
# round's module scope.)
PRIOR_ONLY_AREAS = ["papers", "mcp"]

SEV_ORDER = ["critical", "high", "medium", "low", "info"]
INDIV = {"critical", "high", "medium"}  # non-autofix -> individual issue
GROUP = {"low", "info"}  # non-autofix -> per-area bucket


def caveat(f):
    if f.get("_debate"):
        return "> Verified by multi-model debate (Gemini+Codex). See verdict below."
    if f.get("_verified"):
        return f"> Verified ({f['_verified']})."
    return "> Generated by `/super-qa`, agent analysis — review before action (not source-verified)."


def finding_body(f):
    L = [
        caveat(f),
        "",
        "## Problem",
        f["description"],
        "",
        "## Location",
        f"`{f['location']}`",
        "",
        "## Suggested approach",
        f.get("suggested_fix") or "_(see description)_",
        "",
    ]
    if f.get("_debate"):
        d = f["_debate"]
        L += [
            "## Debate verdict",
            f"- original **{d['original']}** · gemini **{d['gemini']}** · codex **{d['codex']}** "
            f"-> verdict **{d['verdict']}**",
            f"- {d['synthesis']}",
            "",
        ]
    L += [
        "## Acceptance criteria",
        "- [ ] Resolved at the cited location",
        "- [ ] Regression test added (`uv run pytest`)",
        "- [ ] `ruff check` + type check clean",
        "",
    ]
    refs = ", ".join(f.get("references") or []) or "—"
    L += [
        "## Metadata",
        f"- **Finding ID:** `{f['id']}` · **fingerprint:** `{f['fingerprint']}`",
        f"- **Category:** {f['category']} · **Area:** `area:{f['_area']}` · "
        f"**Type:** `type:{f['_type']}` · **Auto-fixable:** {'yes' if f.get('auto_fixable') else 'no'}",
        f"- **Lens:** {f.get('_lens')} · **References:** {refs}",
        f"- **Filter:** `label:area:{f['_area']}` + `label:severity:{f['severity']}`",
        "",
        f"<!-- super-qa-key: find:{f['id']} -->",
    ]
    return "\n".join(L)


def group_body(area, items):
    L = [
        f"> Grouped non-autofixable **low/info** findings for `area:{area}` ({len(items)}). "
        "Agent analysis — review before action.",
        "",
    ]
    for f in sorted(items, key=lambda x: SEV_ORDER.index(x["severity"])):
        L.append(
            f"- **{f['severity']}** `{f['location']}` — {f['title']} "
            f"(`{f['id']}`, fp `{f['fingerprint']}`)"
        )
    L += ["", f"<!-- super-qa-key: group:li:{area} -->"]
    return "\n".join(L)


def autofix_body(sev, items):
    L = [
        f"> Mechanically auto-fixable **{sev}** findings ({len(items)}). Apply via `/super-qa` Phase 3.",
        "",
        "| ID | Location | Title | Suggested fix |",
        "| --- | --- | --- | --- |",
    ]
    for f in items:
        fix = (
            (f.get("suggested_fix") or "").replace("\n", " ").replace("|", "\\|")[:140]
        )
        L.append(
            f"| `{f['id']}` | `{f['location']}` | {f['title'][:70].replace('|', '')} | {fix} |"
        )
    L += ["", f"<!-- super-qa-key: autofix:{sev} -->"]
    return "\n".join(L)


def main():
    findings = json.load(open(CONS))
    dupe = {k: v for k, v in json.load(open(DUPE)).items() if not k.startswith("_")}

    manifest = []
    links_existing = {}  # prior_issue_number -> area_epic_key
    dupe_of = {}  # finding_id -> prior_issue_number

    # partition non-dupe findings
    indiv, groups, autofix = [], defaultdict(list), defaultdict(list)
    areas_with_content = set()
    for f in findings:
        if f["fingerprint"] in dupe:
            old = dupe[f["fingerprint"]]["issue"]
            dupe_of[f["id"]] = old
            links_existing[str(old)] = f"epic:area:{f['_area']}"
            areas_with_content.add(f["_area"])
            continue
        areas_with_content.add(f["_area"])
        if f.get("auto_fixable"):
            autofix[f["severity"]].append(f)
        elif f["severity"] in INDIV:
            indiv.append(f)
        else:
            groups[f["_area"]].append(f)

    all_areas = sorted(areas_with_content | set(PRIOR_ONLY_AREAS))

    # severity breakdown per area (non-dupe individual + grouped) for epic bodies
    area_sev = defaultdict(Counter)
    for f in indiv:
        area_sev[f["_area"]][f["severity"]] += 1
    for area, items in groups.items():
        for f in items:
            area_sev[area][f["severity"]] += 1

    # ---- MASTER epic ----
    manifest.append(
        {
            "key": "epic:master",
            "kind": "master",
            "parent": None,
            "severity": None,
            "title": f"[super-qa] master epic — round 2 ({RUN})",
            "labels": ["super-qa", "type:epic"],
            "body": (
                f"Master umbrella for the `/super-qa` round-2 sweep ({RUN}; "
                f"{len(findings)} findings across 6 audited units).\n\n"
                "Children: per-area epics + the auto-fix epic. Per-severity **observer** "
                "issues index every non-autofixable finding by #. Prior-round issues "
                "(#181-233, ~3mo old) are relabeled and linked into their area epics for "
                "reconciliation.\n\n"
                "Artifacts: `qa/super-qa/runs/" + RUN + "/`\n\n"
                "<!-- super-qa-key: epic:master -->"
            ),
        }
    )

    # ---- AUTOFIX epic ----
    manifest.append(
        {
            "key": "epic:autofix",
            "kind": "autofix-epic",
            "parent": "epic:master",
            "severity": None,
            "title": f"[super-qa] auto-fix epic — round 2 ({RUN})",
            "labels": ["super-qa", "type:epic", "super-qa:auto-fix"],
            "body": (
                "Umbrella for all mechanically auto-fixable findings, grouped one issue per "
                "severity. Apply via `/super-qa` Phase 3.\n\n<!-- super-qa-key: epic:autofix -->"
            ),
        }
    )

    # ---- AREA epics ----
    for area in all_areas:
        bd = " · ".join(
            f"{s}: {area_sev[area][s]}" for s in SEV_ORDER if area_sev[area][s]
        )
        prior = (
            " Also parents relabeled prior-round issues."
            if area in PRIOR_ONLY_AREAS
            else ""
        )
        manifest.append(
            {
                "key": f"epic:area:{area}",
                "kind": "area-epic",
                "parent": "epic:master",
                "severity": None,
                "title": f"[super-qa] area epic: {area} — round 2 ({RUN})",
                "labels": ["super-qa", "type:epic", f"area:{area}"],
                "body": (
                    f"All `/super-qa` round-2 ({RUN}) findings in `area:{area}`. "
                    "Non-autofixable critical/high/medium are individual sub-issues; "
                    f"low/info are one grouped sub-issue.{prior}\n\n"
                    f"**New-finding breakdown:** {bd or '(none — retrofit only)'}\n\n"
                    f"Filter: `label:area:{area}` or `parent-issue:#<this>`\n\n"
                    f"<!-- super-qa-key: epic:area:{area} -->"
                ),
            }
        )

    # ---- individual finding issues ----
    for f in sorted(indiv, key=lambda x: (SEV_ORDER.index(x["severity"]), x["_area"])):
        sev_labels = [f"severity:{f['severity']}"]
        labels = ["super-qa", f"area:{f['_area']}", f"type:{f['_type']}"] + sev_labels
        if f.get("fallback_used"):
            labels.append("super-qa:security-fallback")
        manifest.append(
            {
                "key": f"find:{f['id']}",
                "kind": "finding",
                "parent": f"epic:area:{f['_area']}",
                "severity": f["severity"],
                "title": f"[super-qa] {f['severity']}: {f['title'][:80]}",
                "labels": labels,
                "body": finding_body(f),
            }
        )

    # ---- per-area low/info buckets ----
    for area in sorted(groups):
        items = groups[area]
        manifest.append(
            {
                "key": f"group:li:{area}",
                "kind": "li-group",
                "parent": f"epic:area:{area}",
                "severity": "low",
                "title": f"[super-qa] low/info findings: {area} ({len(items)})",
                "labels": ["super-qa", f"area:{area}", "severity:low"],
                "body": group_body(area, items),
            }
        )

    # ---- autofix per-severity buckets ----
    for sev in SEV_ORDER:
        if not autofix[sev]:
            continue
        manifest.append(
            {
                "key": f"autofix:{sev}",
                "kind": "autofix",
                "parent": "epic:autofix",
                "severity": sev,
                "title": f"[super-qa] auto-fix: {sev} findings ({len(autofix[sev])})",
                "labels": ["super-qa", "super-qa:auto-fix", f"severity:{sev}"],
                "body": autofix_body(sev, autofix[sev]),
            }
        )

    # ---- observer (per non-autofix severity) ----
    # observers list: individual issues of that sev (high/med) and bucket issues (low/info)
    for sev in SEV_ORDER:
        has = any(f["severity"] == sev for f in indiv) or (
            sev in GROUP
            and any(any(x["severity"] == sev for x in groups[a]) for a in groups)
        )
        if not has:
            continue
        manifest.append(
            {
                "key": f"observer:{sev}",
                "kind": "observer",
                "parent": "epic:master",
                "severity": sev,
                "title": f"[super-qa] index: all {sev} findings",
                "labels": ["super-qa", f"severity:{sev}"],
                "body": (
                    f"> Index/listing of non-autofixable **{sev}** findings. "
                    "Populated with issue #refs at filing time.\n\n## Issues\n_(patched)_\n\n"
                    f"<!-- super-qa-key: observer:{sev} -->"
                ),
            }
        )

    out = {
        "run": RUN,
        "manifest": manifest,
        "dupe_of": dupe_of,
        "links_existing": links_existing,
        "all_areas": all_areas,
    }
    json.dump(out, open(OUT, "w"), indent=2)

    kinds = Counter(m["kind"] for m in manifest)
    print(f"wrote {OUT}")
    print(f"manifest entries: {len(manifest)}  ", dict(kinds))
    print(
        f"individual={len(indiv)} | li-groups={len(groups)} | "
        f"autofix-buckets={sum(1 for s in SEV_ORDER if autofix[s])} | "
        f"areas={len(all_areas)} {all_areas}"
    )
    print(
        f"dupes (skip new, link old): {len(dupe_of)} -> issues {sorted(set(dupe_of.values()))}"
    )
    print(f"links_existing: {links_existing}")
    af_total = sum(len(autofix[s]) for s in SEV_ORDER)
    print(
        f"autofix findings folded into {sum(1 for s in SEV_ORDER if autofix[s])} buckets: {af_total}"
    )


if __name__ == "__main__":
    main()
