#!/usr/bin/env bash
# setup-projects.sh — create the 4 GitHub Projects + custom fields (idempotent).
#
# Projects/fields are NOT idempotent in gh, so this checks-before-creates
# throughout. Creates (if absent):
#   KB — Main, KB — Critical Path to Phase 4,
#   KB — Bug & Security Triage, KB — Research & Eval
# On KB — Main and KB — Critical Path it ensures custom single-select fields:
#   Priority [Critical, High, Medium, Low]
#   Phase    [2.5c,3A,3B,3C,3D,3E,3F,3G,3H,3I,4,4+,Deferred]
#
# It does NOT (cannot via gh):
#   - add "In Review" to the built-in Status field   -> USER does this in the UI
#   - create any board/table view                     -> USER does this in the UI
#
# Output: scripts/.pm-ids.env (gitignored) — project numbers, node-ids, field-ids
# and per-option ids, consumed by migrate-issues.sh and to fill workflow YAML.
#
# Usage:
#   scripts/setup-projects.sh --dry-run
#   scripts/setup-projects.sh

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/pm-common.sh
source "$HERE/lib/pm-common.sh"
parse_common_args "$@"
case "${PM_ARGS[0]:-}" in --help)
	sed -n '2,28p' "$0"
	exit 0
	;;
esac
preflight

IDS_ENV="$HERE/.pm-ids.env"
PROJECTS=(
	"KB — Main"
	"KB — Critical Path to Phase 4"
	"KB — Bug & Security Triage"
	"KB — Research & Eval"
)
PHASE_OPTS="2.5c,3A,3B,3C,3D,3E,3F,3G,3H,3I,4,4+,Deferred"
PRIORITY_OPTS="Critical,High,Medium,Low"

# Find a project number by exact title, else empty.
project_number() {
	gh project list --owner "$OWNER" --format json \
		--jq '(.projects // [])[] | select(.title == $t) | .number' --arg t "$1" 2>/dev/null | head -1
}
project_field_names() {
	gh project field-list "$1" --owner "$OWNER" --format json \
		--jq '[(.fields // [])[].name] | join(",")' 2>/dev/null || echo ""
}

ensure_project() {
	local title="$1" num
	num="$(project_number "$title")"
	if [[ -n "$num" ]]; then
		log "project exists: #$num '$title'"
	else
		if [[ "$DRY_RUN" == "1" ]]; then
			run gh project create --owner "$OWNER" --title "$title"
			num="<new>"
		else
			gh project create --owner "$OWNER" --title "$title" >/dev/null
			num="$(project_number "$title")"
			ok "created project #$num '$title'"
		fi
	fi
	printf '%s' "$num"
}

ensure_select_field() {
	local num="$1" field="$2" opts="$3" existing
	[[ "$num" == "<new>" ]] && {
		run gh project field-create "$num" --owner "$OWNER" --name "$field" --data-type SINGLE_SELECT --single-select-options "$opts"
		return
	}
	existing="$(project_field_names "$num")"
	if [[ ",$existing," == *",$field,"* ]]; then
		log "  field '$field' exists on #$num, skip"
	else
		run gh project field-create "$num" --owner "$OWNER" --name "$field" --data-type SINGLE_SELECT --single-select-options "$opts"
		ok "  created field '$field' on #$num"
	fi
}

declare -A NUM
log "== ensure 4 projects =="
for t in "${PROJECTS[@]}"; do NUM["$t"]="$(ensure_project "$t")"; done

log "== ensure custom fields on Main + Critical Path =="
for t in "KB — Main" "KB — Critical Path to Phase 4"; do
	ensure_select_field "${NUM[$t]}" "Priority" "$PRIORITY_OPTS"
	ensure_select_field "${NUM[$t]}" "Phase" "$PHASE_OPTS"
done

# ---- write .pm-ids.env ------------------------------------------------------
# Captures project node-ids, field-ids, and per-option ids that migrate-issues.sh
# needs (item-edit targets ids, not human names).
write_ids_env() {
	local main="${NUM["KB — Main"]}"
	[[ "$DRY_RUN" == "1" || "$main" == "<new>" || -z "$main" ]] && {
		warn "skipping .pm-ids.env (dry-run or project not materialised)"
		return 0
	}

	log "resolving field/option ids for Main (#$main)…"
	local fj
	fj="$(gh project field-list "$main" --owner "$OWNER" --format json 2>/dev/null)"
	local main_pid phase_fid prio_fid
	main_pid="$(gh project view "$main" --owner "$OWNER" --format json --jq '.id' 2>/dev/null)"
	phase_fid="$(jq -r '(.fields // [])[] | select(.name=="Phase") | .id' <<<"$fj")"
	prio_fid="$(jq -r '(.fields // [])[] | select(.name=="Priority") | .id' <<<"$fj")"

	{
		echo "# generated by setup-projects.sh — gitignored — ids for migrate-issues.sh + workflow YAML"
		echo "OWNER=$OWNER"
		echo "MAIN_NUMBER=$main"
		echo "MAIN_PID=$main_pid"
		echo "TRIAGE_NUMBER=${NUM["KB — Bug & Security Triage"]}"
		echo "RESEARCH_NUMBER=${NUM["KB — Research & Eval"]}"
		echo "CRITPATH_NUMBER=${NUM["KB — Critical Path to Phase 4"]}"
		echo "PHASE_FIELD_ID=$phase_fid"
		echo "PRIORITY_FIELD_ID=$prio_fid"
		# per-option ids
		jq -r '(.fields // [])[] | select(.name=="Phase") | (.options // [])[] | "PHASE_OPT_" + (.name|gsub("[^A-Za-z0-9]";"_")) + "=" + .id' <<<"$fj"
		jq -r '(.fields // [])[] | select(.name=="Priority") | (.options // [])[] | "PRIO_OPT_" + (.name|gsub("[^A-Za-z0-9]";"_")) + "=" + .id' <<<"$fj"
	} >"$IDS_ENV"
	ok "wrote $IDS_ENV"
}
write_ids_env

# ---- USER reminders (gh cannot do these) ------------------------------------
cat >&2 <<'REMIND'

  ┌─ USER ACTIONS (gh cannot script these) ───────────────────────────────────┐
  │ 1. KB — Main → Settings → Status field → + add option "In Review"          │
  │    (place between "In Progress" and "Done").                               │
  │ 2. Build the saved views/boards per the view-spec sheet in                 │
  │    docs/plans/2026-06-01-github-project-management.md §5 (Phase 4).         │
  │ 3. Create classic PAT (scopes: repo, project) →                            │
  │    gh secret set KB_PROJECT_TOKEN -R OWNER/REPO                            │
  └────────────────────────────────────────────────────────────────────────────┘
REMIND

ok "setup-projects complete (dry_run=$DRY_RUN)"
